#!/bin/bash
# /etc/init.d/nerf-sightd
# sudo chmod +x /etc/init.d/nerf-sightd
# sudo update-rc.d nerf-sightd defaults
# service nerf-sightd start OR service nerf-sightd stop

### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: nerfSight initscript
# Description: This service is used to manage a led
### END INIT INFO
  
case "$1" in
  start)
    echo "Starting Sight"
    /home/nerfpi/nerf-sight.py &
    ;;
  stop)
    echo "Stopping Sight"
    #killall nerf-sight.py
    kill $(ps aux | grep -m 1 'python /home/nerfpi/nerf-sight.py' | awk '{ print $2 }')
    ;;
  *)
    echo "Usage: service nerf-sightd start|stop"
    exit 1
    ;;
esac
exit 0
